import type { Metadata } from "next";
import "./globals.css";
import Banner from "../components/banner";
import Nav from "../components/nav";
import Footer from "../components/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex flex-col">
        <Banner />
        <Nav />
        {children}
        <Footer />
      </body>
    </html>
  );
}
